travis:
  secure:
    BINSTAR_TOKEN: MAFiJuZ8zRAAxUER0km3aXD0Xno4LA4Nawg2DP1M3Yip6hQBcRKe70rBTGGGuGT5AMeKL1DfQri0GYNkqO9KZZo77BRIdbbNc8ZoPPtR+k+KwNX5Hs81QLP5PCuYuxVJNy3wW381G0y5h0J4RvBGKGtqdZvlFV3120V6Vk44qaU2E0u8+PMndrcW3QYd/nCK6gE2rH8il+E2nSUQ7IobTy1koWSUkIQxKIK4CRAUhLM+bqjQ0j7N1UIkKMLzaVNTbmWRvpvDSUpc0vHvRmTSnCsqsb5EipW12IhAFBqe65Z8Re+YuQc4KOOGXpNbnH8ymVXlYN2H9yA7iwR0ewBeOLcJ8SsUXoykxLJ1wulvepqMpJ1pm2TmVLf0pzGGaEQgovVz3gSEsZn6UOyHQSoTTbnIXxt8pMTIS+DZKxMWOpae1ckoVR9C6Z9JK4pnScq2ra2H011jcq9Ctd1NaaNJHihe/iPad8pPw+tqIwuZivspZs6F+WIBcGcU3jIr3E1CI6IFgoTTG0e3gczrBjAbGIPYrCUQyw2wTkNzb+9ckWr2vGTUi3qAbxOjbMQbUTG65sopDt2UL+8AUy2hHZQn2fWYOVMy/qhx9bdUD2NMBPpVB+HR2HZyZoUkD/dVkcraI3Ec+BSOitutztBOA+9unsY6OdEFhFip60rNAT/tRiY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
